database_url = "postgres://localhost/axum_template"
address = "127.0.0.1:3000" # optional
public_domain = "https://my-app.up.railway.app" # optional
[oauth]
is_enabled = true
[oauth.github] # https://github.com/settings/applications
id=""
secret=""